- name: RA-1 configuration
  hosts: ra-1
  roles:
    - role: dotnet-base
    - role: setup-dotnet-app
      app_dir: gpx
      app_description: GPX Generator app
      app_port: 8800
      app_dll: GPX.Api.dll
      app_domain: gpx.dszymanski.pl
      app_full_stack: true
  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: azure
        state: present
        key: "{{ lookup('file', './azure_rsa.pub') }}"