---
# tasks file for base-nginx

- name: Copy default nginx file
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - Reload nginx

- name: Create snippets directory if it does not exist
  ansible.builtin.file:
    path: /etc/nginx/snippets
    state: directory
    mode: '0755'

- name: Copy ssl params snippet
  copy:
    src: ssl-params
    dest: /etc/nginx/snippets/ssl-params

- name: Copy gzip snippet
  copy:
    src: gzip
    dest: /etc/nginx/snippets/gzip

- name: check if dhparam file exists
  stat: 
    path: /etc/ssl/dhparam.pem
  register: dhparam_file

- name: Generate Diffie-Hellman parameters with the default size (4096 bits)
  community.crypto.openssl_dhparam:
    path: /etc/ssl/dhparam.pem
  when: dhparam_file.stat.exists == False
